name: Test

on: [push]

jobs:
  tests:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn test